FROM golang:latest as builder

WORKDIR /app

COPY go.mod main.go ./

RUN CGO_ENABLED=0 go build -ldflags '-w -s' -o hello-fullcycle .

FROM scratch

COPY --from=builder /app/hello-fullcycle /hello-fullcycle

CMD ["/hello-fullcycle"]